name: CSS Lint

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main, push ]

jobs:
    lint-css:
        runs-on: ubuntu-latest
        name: Lint CSS
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: "18"

            - name: Install stylelint and plugins
              run: npm install -g stylelint stylelint-config-standard

            - name: Create stylelint config
              run: |
                echo '{
                    "extends": "stylelint-config-standard",
                    "rules": {
                        "color-no-invalid-hex": true,
                        "font-family-no-missing-generic-family-keyword": true,
                        "no-descending-specificity": null,
                        "no-duplicate-selectors": true,
                        "declaration-block-no-duplicate-properties": true,
                        "block-no-empty": true,
                        "selector-pseudo-class-no-unknown": true,
                        "unit-no-unknown": true
                    }
                }' > .stylelintrc.json

            - name: Run stylelint
              run: stylelint "**/*.css"