name: HTML Validation

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main, push ]

jobs:
    validate-html:
        runs-on: ubuntu-latest
        name: Validate HTML
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: "18"

            - name: Install html-validate
              run: npm install -g html-validate

            - name: Validate HTML files
              run: html-validate index.html